from esphome.components.mipi_dbi.models import DriverChip, cmd

from .commands import (
    DFUNCTR,
    FRMCTR1,
    GAMMASET,
    GMCTRN1,
    GMCTRP1,
    PIXFMT,
    PWCTR1,
    PWCTR2,
    VMCTR1,
    VMCTR2,
    VSCRSADD,
)

ILI9341 = DriverChip(
    name="ILI9341",
    initsequence=(
        cmd(
            0xEF,
            0x03,
            0x80,
            0x02,
        ),
        cmd(
            0xCF,
            0x00,
            0xC1,
            0x30,
        ),
        cmd(
            0xED,
            0x64,
            0x03,
            0x12,
            0x81,
        ),
        cmd(
            0xE8,
            0x85,
            0x00,
            0x78,
        ),
        cmd(
            0xCB,
            0x39,
            0x2C,
            0x00,
            0x34,
            0x02,
        ),
        cmd(
            0xF7,
            0x20,
        ),
        cmd(
            0xEA,
            0x00,
            0x00,
        ),
        cmd(
            PWCTR1,
            0x23,
        ),
        cmd(
            PWCTR2,
            0x10,
        ),
        cmd(
            VMCTR1,
            0x3E,
            0x28,
        ),
        cmd(
            VMCTR2,
            0x86,
        ),
        cmd(
            VSCRSADD,
            0x00,
        ),
        cmd(
            PIXFMT,
            0x55,
        ),
        cmd(
            FRMCTR1,
            0x00,
            0x18,
        ),
        cmd(
            DFUNCTR,
            0x08,
            0x82,
            0x27,
            0xF2,
            1,
            0x00,
        ),
        cmd(
            GAMMASET,
            0x01,
        ),
        cmd(
            GMCTRP1,
            0x0F,
            0x31,
            0x2B,
            0x0C,
            0x0E,
            0x08,
            0x4E,
            0xF1,
            0x37,
            0x07,
            0x10,
            0x03,
            0x0E,
            0x09,
            0x00,
        ),
        cmd(
            GMCTRN1,
            0x00,
            0x0E,
            0x14,
            0x03,
            0x11,
            0x07,
            0x31,
            0xC1,
            0x48,
            0x08,
            0x0F,
            0x0C,
            0x31,
            0x36,
            0x0F,
        ),
    ),
)


chips = (ILI9341,)
