esphome:
  name: esp32-co2_12v
  friendly_name: esp32-co2_12v

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "wBsX9rUxJw2Bx0kxRsRr3GhZ6QaBkeudpohFxkkiIqw="

ota:
  - platform: esphome
    password: "217e3a842c780575e731fc679948a57f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Co2Sensor-1 Fallback Hotspot"
    password: "pgyywtM4Nrpg"

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true
  id: bus_a

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
      id: bme_pressure
    humidity:
      name: "BME280 Humidity"
    update_interval: 15s
    address: 0x76
  
  - platform: pasco2
    id: my_pasco2
    name: "Test CO2 12V"
    update_interval: 15s
    #measurement_mode: single_shot
    
    #compensate pressure using BME280
    ambient_pressure_compensation_source: bme_pressure

light:
  - platform: status_led
    name: sys_status
    pin:
      number: GPIO8
      inverted: True
    internal: True
    restore_mode: ALWAYS_OFF

web_server:
  port: 80
  include_internal: True
  version: 2

#external_components:
#  - source:
#      type: local
#      path: external/

#external_components:
#  - source: github://pr#8175
#    components: pasco2
#    refresh: 0s

button:
  - platform: template
    name: "Test Calibration"
    on_press:
      - pasco2.perform_forced_calibration:
          value: 400   
          id: my_pasco2
      



