nrf52:
  board: xiao_ble

esphome:
  name: nrf52-ot

api:

logger:
  level: DEBUG
  logs:
    switch: NONE

switch:
  - platform: gpio
    name: "Led Light"
    icon: "mdi:restart"
    pin:
      number: P0.06
      inverted: true
    id: gpio_15

# Enable IPv6 networking
network:
  enable_ipv6: true

# Enable OpenThread
zephyr_openthread:
  channel: 25
  panid: 0xe064
  network_name: "MyHome5"
  xpanid: "1db74a0a3797454b"
  network_key: "00112233445566778899AABBCCDDEEFF"
  pskc: "00112233445566778899AABBCCDDEEFF"
  force_dataset: true
  shell: false

# Add a text sensor to display the IPv6 address
text_sensor:
  - platform: template
    name: "Thread IPv6 Address"
    id: thread_ipv6
    update_interval: 60s
    lambda: |-
      if (zephyr_openthread::global_openthread_component->has_ipv6_address()) {
        return zephyr_openthread::global_openthread_component->get_ipv6_address();
      }
      return {"No IPv6 Address"};
