# These substitutions allow the end user to override certain values
substitutions:
  name: "lum-iot-test"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    # version: 5.1.5

esphome:
  name: "${name}"
  platformio_options:
    upload_speed: 115200

# To be able to get logs from the device via serial and api.
logger:
  level: verbose

espnow:
  auto_add_peer: false
  peers:
    - FF:FF:FF:FF:FF:FF
  on_new_peer:
    - logger.log:
        format: "New peer detected '%u',  error: %d"
        args: [peer_address, errorcode]

  on_received:
    - logger.log:
        format: "Received from '%u'"
        args: [peer_address]

  on_broadcasted:
    - logger.log:
        format: "Broadcasted from '%u'"
        args: [peer_address]

  on_sent_succeed:
    - logger.log:
        format: "sent succeed '%u'"
        args: [peer_address]
  on_sent_failed:
    - logger.log:
        format: "sent failed: '%u' error: %d"
        args: [peer_address, errorcode]

interval:
  - interval: 30sec
    startup_delay: 20sec
    then:
      - logger.log:
          format: "Broadcast message"
      - espnow.broadcast:
          payload: "tesing the test"
