# These substitutions allow the end user to override certain values
substitutions:
  name: "lum-iot-test"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    # version: 5.1.5

esphome:
  name: "${name}"
  platformio_options:
    upload_speed: 115200

# To be able to get logs from the device via serial and api.
logger:
  level: verbose

espnow:
  auto_add_peer: true
  id: esp_now
  on_new_peer:
    - logger.log:
        format: "New peer detected: %s,  error: %d"
        args: [esp_now->peer_string(peer_address).c_str(), (errorcode)]

  on_received:
    - logger.log:
        format: "Received from: %s"
        args: [esp_now->peer_string(peer_address).c_str()]

  on_broadcasted:
    - logger.log:
        format: "Broadcasted from: %s"
        args: [esp_now->peer_string(peer_address).c_str()]

  on_sent_succeed:
    - logger.log:
        format: "sent succeed %s"
        args: [esp_now->peer_string(peer_address).c_str()]
  on_sent_failed:
    - logger.log:
        format: "sent failed: %s error: %d"
        args: [esp_now->peer_string(peer_address).c_str(), (errorcode)]

interval:
  - interval: 30sec
    startup_delay: 20sec
    then:
      - logger.log:
          format: "Broadcast message"
      - espnow.broadcast:
          payload: "tesing the test"
