---
name: pre-commit.ci lite

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
    branches-ignore:
      - beta
      - release

jobs:
  pre-commit-ci-lite:
    name: pre-commit.ci lite
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.2.2
      - name: Run pre-commit.ci lite
        uses: pre-commit-ci/lite-action@v1.0.3
        if: always()
